dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

install: true

git:
  depth: 1

install:
  - go install github.com/gohugoio/hugo
  - npm install -g sass

script:
  - mkdir -p themes/tpanum/static/css
  - sass --update themes/tpanum/scss:themes/tpanum/static/css --style compressed
  - hugo
  - echo panum.dk > public/CNAME

deploy:
  local_dir: public
  repo: tpanum/tpanum.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: thomas@panum.dk
  name: "tpanum"
  on:
    branch: master
