baseurl = "http://panum.dk/"
languageCode = "en-gb"
title = "Blog of Thomas Kobber Panum"

[params]
    name="Thomas Kobber Panum"
    position="Data Scientist"
    company="Tryg"
    companyURL="http://tryg.dk/"
