baseURL = "http://example.org/"
languageCode = "en-us"
title = "Thomas Kobber Panum"
theme = "tpanum"

[params]
author = "Thomas Kobber Panum"
profilepic = "/img/me.png"

github = "tpanum"
email = "thomas_atsign_panum.dk"
linkedin = "tpanum"
twitter = "tpanum"

latestpostcount = 5
